### ISSUE TITLE
Make Entire Panel Clickable 

### ISSUE THREAD

**Issue by sodevan** [deepakpathania/ConnectMe#4]
Make "Edit Your Profile" and "View Other Users"  Panel Clickable . it kind of Confuses A new User.
![screen1](https://cloud.githubusercontent.com/assets/22557976/20607458/73e406e0-b29e-11e6-9e4c-89514cb811ab.png)

**Comment by deepakpathania** [comment]
Thanks for pointing out. Fixed. 
Can be reviewed at : https://github.com/deepakpathania/ConnectMe/commit/92685501c708cab0de3d6ef91ad8ccff347a84dc#diff-67f59a9e18fa697f05c1ac1becf436b2
Closing this now.
